# Generated by Django 4.1.4 on 2022-12-10 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventTypesModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.TextField(help_text="Название события")),
                (
                    "point",
                    models.DecimalField(
                        decimal_places=2, default=0.0, help_text="Кол-во баллов за тип события", max_digits=5
                    ),
                ),
                ("description", models.TextField(default="", help_text="Описание события")),
            ],
            options={
                "db_table": "event-types",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ProductsModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(help_text="Название продукта")),
                ("base_namespace", models.TextField(help_text="Пространство Jira")),
                ("base_chat_id", models.TextField(default="", help_text="Чат для отправки оповещений")),
                ("is_active", models.BooleanField(default=True, help_text="Проект активен?")),
            ],
            options={
                "db_table": "products",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PlansModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(auto_now_add=True, help_text="День когда была сделана запись плана")),
                ("daily", models.DecimalField(decimal_places=2, default=0.0, help_text="Дейли", max_digits=5)),
                (
                    "review_code",
                    models.DecimalField(decimal_places=2, default=0.0, help_text="Ревью кода", max_digits=5),
                ),
                (
                    "one_to_one",
                    models.DecimalField(decimal_places=2, default=0.0, help_text="Один на один", max_digits=5),
                ),
                ("individual_plan", models.DecimalField(decimal_places=2, default=0.0, help_text="ПИР", max_digits=5)),
                (
                    "meeting_on_product",
                    models.DecimalField(
                        decimal_places=2, default=0.0, help_text="Встреча владельца продукта с Полетаевой", max_digits=5
                    ),
                ),
                (
                    "close_task",
                    models.DecimalField(decimal_places=2, default=0.0, help_text="Закрытие задач", max_digits=5),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Продукт",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="product_app.productsmodel",
                    ),
                ),
            ],
            options={
                "db_table": "plans",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="NamespacesModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(help_text="Название пространства Jira")),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Продукт",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="namespaces",
                        to="product_app.productsmodel",
                    ),
                ),
            ],
            options={
                "db_table": "namespaces",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="EventsModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(help_text="Дата проведения события")),
                ("url", models.URLField(help_text="Ссылка на задачу в Jira", null=True)),
                ("description", models.TextField(help_text="Название события", null=True)),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Продукт",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event",
                        to="product_app.productsmodel",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        help_text="Тип события",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="types",
                        to="product_app.eventtypesmodel",
                    ),
                ),
            ],
            options={
                "db_table": "events",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="EmployeesModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("login", models.TextField(help_text="Логин сотрудника")),
                ("full_name", models.TextField(help_text="ФИО сотрудника")),
                ("is_developer", models.BooleanField(default=False, help_text="Разработчик продукта?")),
                ("is_manager", models.BooleanField(default=False, help_text="Руководитель продукта?")),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Продукт",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="product_app.productsmodel",
                    ),
                ),
            ],
            options={
                "db_table": "employees",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ChatsModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(help_text="Название пространства Jira")),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Продукт",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to="product_app.productsmodel",
                    ),
                ),
            ],
            options={
                "db_table": "chats",
                "ordering": ["id"],
            },
        ),
    ]
