# Generated by Django 4.1.4 on 2022-12-13 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0001_create_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plansmodel",
            name="date",
            field=models.DateField(default=datetime.datetime.now, help_text="День когда была сделана запись плана"),
        ),
    ]
