# Generated by Django 4.1.4 on 2022-12-18 06:48

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0002_set_default_date_in_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventtypesmodel",
            name="point",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Кол-во баллов за тип события",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="plansmodel",
            name="close_task",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Закрытие задач",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="plansmodel",
            name="daily",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Дейли",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="plansmodel",
            name="date",
            field=models.DateField(
                default=datetime.date.today,
                help_text="День когда была сделана запись плана",
            ),
        ),
        migrations.AlterField(
            model_name="plansmodel",
            name="individual_plan",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="ПИР",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="plansmodel",
            name="meeting_on_product",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Встреча владельца продукта с Полетаевой",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="plansmodel",
            name="one_to_one",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Один на один",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="plansmodel",
            name="review_code",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Ревью кода",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
