# Generated by Django 4.1.4 on 2022-12-18 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0004_add_many_to_many_chats_and_namespaces_to_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsmodel",
            name="base_chat_id",
            field=models.ForeignKey(
                help_text="Чат для отправки оповещений",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="base_chat_id",
                to="product_app.chatsmodel",
            ),
        ),
        migrations.AlterField(
            model_name="productsmodel",
            name="base_namespace",
            field=models.ForeignKey(
                help_text="Пространство Jira",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="base_namespaces",
                to="product_app.namespacesmodel",
            ),
        ),
        migrations.AlterField(
            model_name="productsmodel",
            name="chats",
            field=models.ManyToManyField(null=True, related_name="chats", to="product_app.chatsmodel"),
        ),
        migrations.AlterField(
            model_name="productsmodel",
            name="namespaces",
            field=models.ManyToManyField(null=True, related_name="namespaces", to="product_app.namespacesmodel"),
        ),
    ]
