# Generated by Django 4.1.4 on 2022-12-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0005_set_null_related_namespaces_chats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeesmodel",
            name="product",
        ),
        migrations.AddField(
            model_name="productsmodel",
            name="employees",
            field=models.ManyToManyField(null=True, related_name="employees", to="product_app.employeesmodel"),
        ),
    ]
