# Generated by Django 4.1.4 on 2022-12-21 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0006_set_null_related_employees_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsmodel",
            name="base_chat_id",
            field=models.ForeignKey(
                blank=True,
                help_text="Чат для отправки оповещений",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="base_chat_id",
                to="product_app.chatsmodel",
            ),
        ),
        migrations.AlterField(
            model_name="productsmodel",
            name="base_namespace",
            field=models.ForeignKey(
                blank=True,
                help_text="Пространство Jira",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="base_namespaces",
                to="product_app.namespacesmodel",
            ),
        ),
    ]
