# Generated by Django 4.1.4 on 2022-12-31 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_init_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeesmodel",
            name="is_developer",
        ),
        migrations.RemoveField(
            model_name="employeesmodel",
            name="is_manager",
        ),
        migrations.RemoveField(
            model_name="productsmodel",
            name="employees",
        ),
        migrations.AddField(
            model_name="productsmodel",
            name="developers",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                help_text="Разработчики продукта",
                null=True,
                related_name="developers",
                to="web.employeesmodel",
            ),
        ),
        migrations.AddField(
            model_name="productsmodel",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Руководитель продукта",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manager",
                to="web.employeesmodel",
            ),
        ),
        migrations.AlterField(
            model_name="productsmodel",
            name="chats",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                help_text="Чаты продукта для оповещений",
                null=True,
                related_name="chats",
                to="web.chatsmodel",
            ),
        ),
        migrations.AlterField(
            model_name="productsmodel",
            name="namespaces",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                help_text="Пространства Jira для поиска задач продукта",
                null=True,
                related_name="namespaces",
                to="web.namespacesmodel",
            ),
        ),
    ]
